name: bechirsegni/music
author:
  name: Omar Achoor
  email: omar.achour@appandweb.de
  url: null
copyright: 2015 Omar Achoor
description: Music web application for tunisian Artists using ruby on rails
